---

policies:
  - name: d-securitygroup-ingress-ipv4
    resource: security-group
    description: >
      Compliance: Ingress configuration|
    mode:
      type: config-rule
      role: arn:aws:iam::{account_id}:role/{custodian_detective_role}
      tags:
        CloudCustodianType: Detective
    filters:
      - and:
          - type: ingress
            Cidr:
              value:
                - 0.0.0.0/0
              op: in
          - tag:__Exception-SecurityGroup: absent
