---

policies:
  - name: d-securitygroup-ingress-ipv6
    resource: security-group
    description: >
      Compliance: Ingress configuration|
    mode:
      type: config-rule
      role: arn:aws:iam::{account_id}:role/{custodian_detective_role}
      tags:
        CloudCustodianType: Detective
    filters:
      - and:
          - type: ingress
            CidrV6:
              value:
                - ::/0
              op: in
          - tag:__Exception-SecurityGroup: absent
