---

policies:
  - name: r-emr-security-config
    resource: aws.emr
    description: >
      Event: RunJobFlow|
      Compliance: Security Configuration|
      Remediation: Delete|
    mode:
      type: cloudtrail
      events:
        - event: RunJobFlow
          source: elasticmapreduce.amazonaws.com
          ids: responseElements.jobFlowId
      timeout: 200
      delay: 5
      role: arn:aws:iam::{account_id}:role/{custodian_responsive_role}
      tags:
        CloudCustodianType: Responsive
    filters:
      - and:
          - type: event
            key: detail.requestParameters.securityConfiguration
            value: absent
          - tag:__Exception-EMRSecurityConfig: absent
    actions:
      #- type: terminate
      - type: notify
        to:
          - arn:aws:sns:{region}:{account_id}:{topic-name}
        Subject: EMR Cluster NONCOMPLIANT
        Message: missing security configuration
        transport:
          type: sns
          topic: "{topic-name}"
